In [1]:
from keras.datasets import imdb # Load the data, keeping only 10,000 of the most frequently occuring words
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = 10000)

E:\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join([reverse_word_index.get(i-3, '?') for i in train_data[0]])

In [3]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))    # Creates an all zero matrix of shape (len(sequences),10K)
    for i,sequence in enumerate(sequences):
        results[i,sequence] = 1                        # Sets specific indices of results[i] to 1s
    return results

# Vectorize training Data
X_train = vectorize_sequences(train_data)

# Vectorize testing Data
X_test = vectorize_sequences(test_data)

In [4]:
class_names = ['negative','positive']

In [5]:
y_train = np.asarray(train_labels).astype('float32')
y_test  = np.asarray(test_labels).astype('float32')

In [6]:
y_test

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [7]:
from keras import models 
from keras import layers 
model = models.Sequential() 
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(16, activation='relu')) 
model.add(layers.Dense(1, activation='sigmoid'))

E:\Anaconda3\lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
from keras import optimizers
from keras import losses 
from keras import metrics 
model.compile(optimizer=optimizers.RMSprop(learning_rate=0.001), loss = losses.binary_crossentropy, metrics = [metrics.binary_accuracy])

In [9]:
X_val = X_train[:10000]
partial_X_train = X_train[10000:] # Labels for validation 
y_val = y_train[:10000] 
partial_y_train = y_train[10000:]

In [10]:
history = model.fit(partial_X_train, partial_y_train, epochs=10, batch_size=512, validation_data=(X_val, y_val))

Epoch 1/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 79s 701ms/step - binary_accuracy: 0.7024 - loss: 0.5908 - val_binary_accuracy: 0.8704 - val_loss: 0.3815
Epoch 2/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - binary_accuracy: 0.8967 - loss: 0.3292 - val_binary_accuracy: 0.8771 - val_loss: 0.3206
Epoch 3/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - binary_accuracy: 0.9214 - loss: 0.2397 - val_binary_accuracy: 0.8857 - val_loss: 0.2876
Epoch 4/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - binary_accuracy: 0.9389 - loss: 0.1884 - val_binary_accuracy: 0.8788 - val_loss: 0.2985
Epoch 5/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - binary_accuracy: 0.9491 - loss: 0.1602 - val_binary_accuracy: 0.8782 - val_loss: 0.2988
Epoch 6/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - binary_accuracy: 0.9592 - loss: 0.1316 - val_binary_accuracy: 0.8743 - val_loss: 0.3164
Epoch 7/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - binary_accuracy: 0.9663 - loss: 0.1154 - val_binary_accuracy: 0.8849 - val_loss: 0.2995
Epoch 8/10


In [11]:
print(X_test[19])

[0. 1. 1. ... 0. 0. 0.]


In [12]:
# Making Predictions for testing data np.set_printoptions(suppress=True) 
import numpy as np

result = model.predict(np.expand_dims(X_test[19],axis=0))
print(result,class_names[int(result[0]>0.5)])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 639ms/step
[[0.01913631]] negative


C:\Users\Stuti\AppData\Local\Temp\ipykernel_6944\2236947004.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(result,class_names[int(result[0]>0.5)])


In [13]:
print(X_test[0])

[0. 1. 1. ... 0. 0. 0.]


## Dummy Input:
Positive - <br>
1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32

In [14]:
ik = 123
print(train_data[ik])
print(train_labels[ik])
for i in train_data[ik]:
    print(list(word_index.keys())[list(word_index.values()).index(i)],end=" ")

[1, 307, 5, 1301, 20, 1026, 2511, 87, 2775, 52, 116, 5, 31, 7, 4, 91, 1220, 102, 13, 28, 110, 11, 6, 137, 13, 115, 219, 141, 35, 221, 956, 54, 13, 16, 11, 2714, 61, 322, 423, 12, 38, 76, 59, 1803, 72, 8, 2, 23, 5, 967, 12, 38, 85, 62, 358, 99]
1
the version to date on list draw him critical very love to by br of its tony characters was one life this is go was best least should so done result no was with this understood only war couldn't that her get would johnny we in and are to business that her because story use movies 

In [15]:
ik = 12
print(train_data[ik])
print(train_labels[ik])
for i in train_data[ik]:
    print(list(word_index.keys())[list(word_index.values()).index(i)],end=" ")

[1, 13, 119, 954, 189, 1554, 13, 92, 459, 48, 4, 116, 9, 1492, 2291, 42, 726, 4, 1939, 168, 2031, 13, 423, 14, 20, 549, 18, 4, 2, 547, 32, 4, 96, 39, 4, 454, 7, 4, 22, 8, 4, 55, 130, 168, 13, 92, 359, 6, 158, 1511, 2, 42, 6, 1913, 19, 194, 4455, 4121, 6, 114, 8, 72, 21, 465, 9667, 304, 4, 51, 9, 14, 20, 44, 155, 8, 6, 226, 162, 616, 651, 51, 9, 14, 20, 44, 10, 10, 14, 218, 4843, 629, 42, 3017, 21, 48, 25, 28, 35, 534, 5, 6, 320, 8, 516, 5, 42, 25, 181, 8, 130, 56, 547, 3571, 5, 1471, 851, 14, 2286]
0
the was did hands fact absolute was then laugh what of love it notice matters it's similar of numerous few blind was couldn't as on type but of and slow an of too or of 5 br of you in of time here few was then kids is didn't billy and it's is rubbish film thought rotten carl is little in we not seemed paperhouse beautiful of when it as on has 10 in is script actually sad happy when it as on has i i as interesting seeks hero it's nine not what have one so stories to is star in car to it's h

In [16]:
user = []

dyna = input("Enter: ").split(",")
for x in dyna:
    user.append(int(x))

user=vectorize_sequences(user)
result1 = model.predict(np.expand_dims(user[1],axis=0))
print()
print(result1,class_names[int(result1[0]>0.5)])

Enter: 1, 13, 119, 954, 189, 1554, 13, 92, 459, 48, 4, 116, 9, 1492, 2291, 42, 726, 4, 1939, 168, 2031, 13, 423, 14, 20, 549, 18, 4, 2, 547, 32, 4, 96, 39, 4, 454, 7, 4, 22, 8, 4, 55, 130, 168, 13, 92, 359, 6, 158, 1511, 2, 42, 6, 1913, 19, 194, 4455, 4121, 6, 114, 8, 72, 21, 465, 9667, 304, 4, 51, 9, 14, 20, 44, 155, 8, 6, 226, 162, 616, 651, 51, 9, 14, 20, 44, 10, 10, 14, 218, 4843, 629, 42, 3017, 21, 48, 25, 28, 35, 534, 5, 6, 320, 8, 516, 5, 42, 25, 181, 8, 130, 56, 547, 3571, 5, 1471, 851, 14, 2286
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

[[0.52743053]] positive


C:\Users\Stuti\AppData\Local\Temp\ipykernel_6944\1212207043.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(result1,class_names[int(result1[0]>0.5)])


In [17]:
#word

Negative - everything is not working we will die<br>
Positive - everything is working very well excellent work

In [19]:
get_phrase = input("Enter: ")

vec_words = []

for i in get_phrase.split(" "):
    vec_words.append(word_index[i.lower()])
    
vec_words = vectorize_sequences(vec_words)
result = []
#print(vec_words)
for j in range(len(vec_words)):
    result99 = model.predict(np.expand_dims(vec_words[j],axis=0))
    #print(result99[0],class_names[int(result99[0]>0.5)])
    result.append(class_names[int(result99[0]>0.5)])


if result.count('negative')> result.count('positive'):
    print("NEGATIVE")
else:
    print("POSITIVE")

Enter: everything is working very well excellent work
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

C:\Users\Stuti\AppData\Local\Temp\ipykernel_6944\931124717.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result.append(class_names[int(result99[0]>0.5)])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
POSITIVE


In [ ]:
import tkinter as tk
import numpy as np

# Function to handle button click
def display_name_and_predict():
    # Get the name from the input field
    name = entry.get()   
    
    vec_words = []
    review_result = []

    for i in name.split(" "):
        vec_words.append(word_index[i.lower()])

    vec_words = vectorize_sequences(vec_words)
    result = []
    #print(vec_words)
    for j in range(len(vec_words)):
        result99 = model.predict(np.expand_dims(vec_words[j],axis=0))
        #print(result99[0],class_names[int(result99[0]>0.5)])
        result.append(result99[0][0])
        review_result.append(class_names[int(result99[0]>0.5)])

    mean = sum(result)/len(result)
    print(review_result)
    final = ''
    if review_result.count('negative')> review_result.count('positive'):
        final = "NEGATIVE"
    else:
        final = "POSITIVE"
    
    # Display the name on the label
    label.config(text=f"Comment is {round(mean,3)}% {final}!")

# Create the main window
window = tk.Tk()
window.title("Name Display and Prediction App")

# Create an input field
entry = tk.Entry(window, width=60)
entry.pack(pady=10)

# Create a button
button = tk.Button(window, text="Predict", command=display_name_and_predict)
button.pack(pady=10)

# Create a display label
label = tk.Label(window, text="")
label.pack(pady=10)

# Run the Tkinter event loop
window.mainloop()
